name: inventory_count
description: ""
publish_to: 'none'
version: 0.1.11
environment:
  sdk: ^3.10.4
dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.3.1
  hive_flutter: ^1.1.0
  provider: ^6.1.5+1
  intl: ^0.20.2
  animated_tree_view: ^2.3.0
  file_picker: ^10.3.8
  supabase_flutter: ^2.12.0
  window_manager: ^0.5.1
  win32: ^5.15.0
  ffi: ^2.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
flutter:
  uses-material-design: true
  assets:
    - assets/PrintCount.vbs
    - assets/VbsJson.vbs
